CREATE TYPE user_roles AS ENUM ('admin','member');

CREATE TABLE users (
    id TEXT PRIMARY KEY,
    name VARCHAR(70) NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    phone VARCHAR(30) NOT NULL UNIQUE,
    role USER_ROLES,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)